import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-fixed-asset-depreciation-tax-recovery",
  "engine": "recovery",
  "title": "Fixed Asset Depreciation Tax Recovery",
  "shortTitle": "Fixed Asset Depreciation Tax Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through fixed asset depreciation tax recovery",
  "industry": "Corporate Tax Asset Recovery",
  "uiPort": 4631,
  "apiPort": 5631,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Fixed Asset Depreciation Tax Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "realizedBenefit",
    "expectedKey": "eligibleBenefit",
    "actualLabel": "Realized Tax Benefit",
    "expectedLabel": "Calculated Eligible Benefit",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Fixed Asset Depreciation Tax Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("asset-register-ingestion","FAD01","Asset register ingestion","Execute asset register ingestion using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed asset register ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Asset register ingestion Reference","text","FAD01-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("invoice-project-mapping","FAD02","Invoice project mapping","Execute invoice project mapping using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed invoice project mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Invoice project mapping Reference","text","FAD02-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("asset-classification","FAD03","Asset classification","Execute asset classification using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed asset classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Asset classification Reference","text","FAD03-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("placed-in-service-validation","FAD04","Placed-in-service validation","Execute placed-in-service validation using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed placed-in-service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Placed-in-service validation Reference","text","FAD04-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("tax-life-method-assignment","FAD05","Tax life method assignment","Execute tax life method assignment using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed tax life method assignment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Tax life method assignment Reference","text","FAD05-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("bonus-depreciation-calculation","FAD06","Bonus depreciation calculation","Execute bonus depreciation calculation using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed bonus depreciation calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Bonus depreciation calculation Reference","text","FAD06-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("section-179-analysis","FAD07","Section 179 analysis","Execute section 179 analysis using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed section 179 analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Section 179 analysis Reference","text","FAD07-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("cost-segregation","FAD08","Cost segregation","Execute cost segregation using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed cost segregation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Cost segregation Reference","text","FAD08-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("repair-versus-capital-determination","FAD09","Repair versus capital determination","Execute repair versus capital determination using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed repair versus capital determination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Repair versus capital determination Reference","text","FAD09-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("partial-disposition-analysis","FAD10","Partial disposition analysis","Execute partial disposition analysis using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed partial disposition analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Partial disposition analysis Reference","text","FAD10-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("retirement-disposal-tracking","FAD11","Retirement disposal tracking","Execute retirement disposal tracking using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed retirement disposal tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Retirement disposal tracking Reference","text","FAD11-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("book-to-tax-reconciliation","FAD12","Book-to-tax reconciliation","Execute book-to-tax reconciliation using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed book-to-tax reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Book-to-tax reconciliation Reference","text","FAD12-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("tax-schedule-generation","FAD13","Tax schedule generation","Execute tax schedule generation using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed tax schedule generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Tax schedule generation Reference","text","FAD13-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("amended-return-support","FAD14","Amended return support","Execute amended return support using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed amended return support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Amended return support Reference","text","FAD14-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]}),
feature("tax-benefit-analytics","FAD15","Tax benefit analytics","Execute tax benefit analytics using fixed asset registers, invoices, projects, asset classifications, service dates, tax lives, methods, bonus depreciation, Section 179, cost segregation, repairs, dispositions, and returns.","Produce a governed tax benefit analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Asset Population","text","Taxpayer / Asset Population · Standard Case"],["caseReference","Tax benefit analytics Reference","text","FAD15-2026-001"],["realizedBenefit","Realized Tax Benefit","currency",1160000],["eligibleBenefit","Calculated Eligible Benefit","currency",1368800],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedBenefit",subjects:["Asset register ingestion case","Invoice project mapping case","Asset classification case","Placed-in-service validation case","Tax life method assignment case"]})
]);
